SiLeBAT/fcl-client

src/app/main-page/container/toolbar-action-container/toolbar-action-container.component.ts
src/app/main-page/presentation/toolbar-action/toolbar-action.component.ts
src/app/tracing/data.model.ts
src/app/tracing/util/map-utils.ts

code is only commented because it might be reactivated soon
ticket: #622
Change-Id: I830071aa2757cdc429656d7e882825ea5165fccf

deactivates Black and White Map

---

src/app/user/presentation/activate/activate.component.html

Delete "Continue to login" button during registration process.

---

src/assets/mxgraph-grapheditor/js/Graph.js

Make landscape view the standard view for the ROA style.

---

package-lock.json

ticket: #636 #642
Change-Id: I6f701812ec75d7d51a644f48b7b2ff70ff8c55b3

bumps (patch) eventsource and async

---

src/app/main-page/presentation/example-menu/example-menu.component.html
src/app/main-page/presentation/toolbar-action/toolbar-action.component.html

Add data-cy properties for e2e tests.

---

src/app/main-page/main-page.module.ts
src/app/main-page/presentation/dialog-save-data/dialog-save-data.component.html
src/app/main-page/presentation/dialog-save-data/dialog-save-data.component.scss
src/app/main-page/presentation/dialog-save-data/dialog-save-data.component.ts
src/app/main-page/presentation/toolbar-action/toolbar-action.component.ts
src/app/tracing/util/constants.ts
src/app/user/presentation/register/__snapshots__/register.component.spec.ts.snap
src/app/user/presentation/reset/__snapshots__/reset.component.spec.ts.snap
src/app/user/services/user.service.spec.ts
src/app/user/services/user.service.ts

Loading of new (example) data set: Trigger save message box.

---

src/app/main-page/presentation/dialog-save-data/dialog-save-data.component.scss
src/app/main-page/presentation/toolbar-action/toolbar-action.component.html
src/app/main-page/presentation/toolbar-action/toolbar-action.component.ts
src/app/main-page/services/main-page.service.ts
src/app/tracing/components/main-tracing.component.ts
src/app/tracing/io/io.effects.ts
src/app/tracing/util/constants.ts

Loading of example data set: Trigger save message box.

---

src/app/tracing/configuration/abstract-rule-edit-view.ts
src/app/tracing/configuration/colors-and-shapes-edit-view/colors-and-shapes-edit-view.component.html
src/app/tracing/configuration/complex-filter-view/complex-filter-view.component.html
src/app/tracing/configuration/complex-filter-view/complex-filter-view.component.ts
src/app/tracing/configuration/configuration.effects.ts
src/app/tracing/configuration/edge-color-edit-view/edge-color-edit-view.component.html
src/app/tracing/configuration/edit-highlighting.service.ts
src/app/tracing/configuration/highlighting-delivery-view/highlighting-delivery-view.component.html
src/app/tracing/configuration/highlighting-delivery/highlighting-delivery.component.html
src/app/tracing/configuration/highlighting-delivery/highlighting-delivery.component.ts
src/app/tracing/configuration/highlighting-element-view/highlighting-element-view.component.ts
src/app/tracing/configuration/highlighting-station-view/highlighting-station-view.component.html
src/app/tracing/configuration/highlighting-station/highlighting-station.component.html
src/app/tracing/configuration/highlighting-station/highlighting-station.component.ts
src/app/tracing/configuration/label-rules-edit-view/label-rules-edit-view.component.html
src/app/tracing/configuration/model.ts
src/app/tracing/configuration/property-selector-view/property-selector-view.component.ts
src/app/tracing/dialog/dialog-select/dialog-select.component.html
src/app/tracing/dialog/dialog-select/dialog-select.component.ts
src/app/tracing/services/table.service.ts

Show available columns sorted alphabetically.

---

src/app/tracing/dialog/station-properties/station-properties.component.ts
src/app/tracing/util/constants.ts

Adapt station properties to new list of VIP variables.

---

src/app/tracing/services/table.service.ts

Change display name of columns in Web App.

---

src/app/tracing/configuration/property-selector-view/property-selector-view.component.html
src/app/tracing/dialog/delivery-properties/delivery-properties.component.ts
src/app/tracing/dialog/station-properties/station-properties.component.ts
src/app/tracing/util/constants.ts

Ticket: #421
Changes as described in the comment:
https://github.com/SiLeBAT/fcl-client/issues/421#issuecomment-1239042234

Implement additional changes in station and delivery properties dialog.

---

src/app/main-page/presentation/toolbar-action/toolbar-action.component.ts
src/app/tracing/dialog/dialog-ok-cancel/dialog-ok-cancel.component.html
src/app/tracing/dialog/dialog-ok-cancel/dialog-ok-cancel.component.ts
src/app/tracing/util/constants.ts

Ticket: #669
Implementation of requests given in pull request comments of ticket #680 : 
https://github.com/SiLeBAT/fcl-client/pull/681#discussion_r970597495
https://github.com/SiLeBAT/fcl-client/pull/681#discussion_r970600460

Trigger save dialogue when uploading own data.

---

src/app/main-page/presentation/dashboard/dashboard.component.html
src/app/main-page/presentation/page-header/page-header.component.html
src/app/main-page/presentation/toolbar-action/toolbar-action.component.html
src/app/main-page/presentation/toolbar-action/toolbar-action.component.ts
src/app/tracing/graph/components/graph-legend-view/graph-legend-view.component.html
src/app/tracing/graph/components/nested-mat-menu-view/nested-mat-menu-view.component.html
src/app/tracing/shared/node-symbol-view/node-symbol-view.component.html
src/app/user/presentation/register/__snapshots__/register.component.spec.ts.snap
src/app/user/presentation/reset/__snapshots__/reset.component.spec.ts.snap

and updates unit test snapshots
ticket: #460
Change-Id: I8cbdacefee9f6919cdd549712012b28a021f3349

adds data-cy attributes for e2e test, refines upload model components

---

src/app/main-page/presentation/toolbar-action/toolbar-action.component.ts

Fix typo in 2-step save dialog.

---

src/app/main-page/container/toolbar-action-container/toolbar-action-container.component.html
src/app/main-page/container/toolbar-action-container/toolbar-action-container.component.ts
src/app/main-page/presentation/toolbar-action/toolbar-action.component.ts
src/app/tracing/data.model.ts
src/app/tracing/graph/components/schema-graph/schema-graph.component.ts
src/app/tracing/io/ext-data-model.v1.ts
src/app/tracing/io/io.actions.ts
src/app/tracing/io/io.effects.ts
src/app/tracing/io/io.service.ts
src/app/tracing/state.model.ts
src/app/tracing/state/tracing.actions.ts
src/app/tracing/state/tracing.reducers.ts
src/app/tracing/state/tracing.selectors.ts
src/app/tracing/tracing.actions.ts
src/app/tracing/tracing.effects.ts

Prevent unnecessary appearance of save dialogue.

---

src/app/main-page/container/toolbar-action-container/toolbar-action-container.component.html
src/app/main-page/container/toolbar-action-container/toolbar-action-container.component.ts
src/app/main-page/presentation/toolbar-action/toolbar-action.component.html
src/app/main-page/presentation/toolbar-action/toolbar-action.component.ts

Ticket: #668
Thanks for pointing out the bug.

Fix bug saving image and opening roa style.

---

src/app/user/presentation/login-view/__snapshots__/login-view.component.spec.ts.snap

- test failed because maintenance message was removed
Change-Id: Ia084ae1c71247dea8098f0c8dbad6d34ba982cf6

updates snapshot

---

src/app/tracing/configuration/filter-table-view/filter-table-view.component.ts
src/app/tracing/services/table.service.ts

Merging this will fix the bug where the data table for deliveries did not distplay the boolean value for the outbreak value of deliveries.

Data table for deliveries: Outbreak column empty #788

---

src/app/tracing/configuration/edit-highlighting.service.ts
src/app/tracing/data.model.ts
src/app/tracing/graph/context-menu.service.ts
src/app/tracing/graph/menu.constants.ts
src/app/tracing/services/edit-tracing-settings.service.ts
src/app/tracing/tracing.actions.ts
src/app/tracing/tracing.effects.ts

- adds graph menu entry kill contamination
- refactoring: replaces interfaces ClearOutbreaksOptions, ClearInvisibilitiesOptions by FoodChainElementTypeSelection
ticket: #775

adds clear kill contamination feature

---

.github/workflows/build.yml
.github/workflows/pull-request-checks.yml

Add a github action running build, lint, and test jobs that runs automatically on pull requests.

Add github actions to pull requests.

---

.scannerwork/report-task.txt
src/app/content/faq/components/faq-section-view.component.ts
src/app/shared/lp-solver.ts
src/app/tracing/configuration/filter-table-view/filter-table-utils.ts
src/app/tracing/configuration/filter-table-view/filter-table-view.component.ts
src/app/tracing/configuration/prefix-editor-view/prefix-editor-view.component.ts
src/app/tracing/dialog/station-properties/station-properties.component.ts
src/app/tracing/graph/components/graph-view/graph-view.component.ts
src/app/tracing/graph/cy-graph/cy-graph.ts
src/app/tracing/graph/gis-positioning.service.ts
src/app/tracing/grouping/isolated-component-collapser.ts
src/app/tracing/io/data-importer/data-importer-v0.ts
src/app/tracing/io/data-importer/data-importer-v1.ts
src/app/tracing/shared/node-symbol-view/node-symbol-view.component.ts
src/app/tracing/state/tracing.selectors.ts
src/app/tracing/util/console-utils.ts
src/app/tracing/util/non-ui-utils.ts
src/app/tracing/visio/layout-engine/station-by-country-grouper.ts
src/app/tracing/visio/property-element-view/property-element-view.component.ts
src/app/tracing/visio/report-configuration/report-configuration.component.ts

For cases where a value is checked for existence, and a default value should be used if it doesn't exist, it is preferred to use the ?? operator rather than ||.
Some places in our code also used ternary operators for this use case.
There where also some default parameters in functions that used incorrect syntax, which have been adjusted.

Use nullish coalescing operators and optional chaining to simplify expressions currently using || or ternary operators.

---

src/app/tracing/configuration/filter-table-view/filter-table-view.component.ts
src/app/tracing/configuration/table-cells/symbol-cell-view/symbol-cell-view.component.html
src/app/tracing/configuration/table-cells/symbol-cell-view/symbol-cell-view.component.ts
src/app/tracing/dialog/station-properties/station-properties.component.ts
src/app/tracing/shared/node-symbol-view/node-symbol-view.component.ts
src/app/tracing/util/constants.ts

Ticket: Filter table shows wrong row icon #818

Fix wrong colors showing in filtertable.

---

src/app/tracing/dialog/station-properties/station-properties.component.html
src/app/tracing/dialog/station-properties/station-properties.component.scss

Make the Station dialogue movable.
Ticket: #803

Make station property dialogue movable

---

package-lock.json

fixes audit issues: bumps micromatch, express and cookie

---

angular.json

adds allowedCommonJsDependencies
- html2canvas
- moment
- exceljs
- immutable
ticket: #868

fixes commonjs dependency warnings

---

src/app/tracing/dialog/station-properties/station-properties.component.html
src/app/tracing/dialog/station-properties/station-properties.component.scss

Station properties component now uses the new movable dialog component.
Ticket #901

Subtask #901: Refactor station properties to use movable dialog

---

src/app/main-page/presentation/main-page/main-page.component.scss

Fixes excess space in footer and header grid rows on very large screens.
Ticket #294

Ticket #294: Fix styling of footer and header

---

src/app/main-page/presentation/toolbar-action/toolbar-action.component.html
src/app/main-page/presentation/toolbar-action/toolbar-action.component.scss
src/material-style.scss

Warning icon is now shown before the file name in toolbar action component. Color of icon is now a bright yellow.
Ticket #950

Ticket #950: Changes styling of warning icon in toolbar action component
