src/app/tracing/tracing.effects.ts
- all selected deliveries/stations but the double clicked deelivery/station
(in filter table) are unselected on double click
ticket: #602
Change-Id: I0a95271cf798fdfc0ddcdf6c3f7e6e763a67108c
=> deletes preexisting selection on double click in filter table

src/app/shared/directives/disable-subscript-wrapper-tab-focus.ts, src/app/shared/shared.module.ts, src/app/user/presentation/register/register.component.html, src/app/user/presentation/register/register.component.ts, src/app/user/presentation/reset/reset.component.html, src/app/user/presentation/reset/reset.component.ts
- adds a new directive that sets the tabIndex to -1 for all child
elements with class .mat-form-field-subscript-wrapper
ticket: #619
Change-Id: I95027b71a8196fffb216b2912f7a41ac1495a12b
=> fixes tab focus problems in firefox for pw reset and registration

src/app/tracing/dialog/delivery-properties/delivery-properties.component.html, src/app/tracing/dialog/delivery-properties/delivery-properties.component.scss, src/app/tracing/dialog/delivery-properties/delivery-properties.component.ts, src/app/tracing/dialog/station-properties/station-properties.component.html, src/app/tracing/dialog/station-properties/station-properties.component.scss, src/app/tracing/dialog/station-properties/station-properties.component.ts, src/app/tracing/io/data-mappings/data-mappings-v1.ts, src/app/tracing/io/ext-data-constants.v1.ts, src/app/tracing/services/table.service.ts, src/app/tracing/tracing.effects.ts
Ticket: #421
Changed station and delivery properties dialog:
vip properties and more properties now have the same organization as columns of the filter table and the highlighting options
=> Change columns display names on station and delivery properties dialog.

src/app/tracing/services/table.service.ts
- instead of favouriteColumns and otherColumns, favouriteColumns have been displayed twice
ticket: #676
Change-Id: I5903473a2a32098e232e90b4185f6a3553b3adfd
=> fixes otherColumns display

src/app/tracing/graph/context-menu.service.ts, src/app/tracing/graph/menu.constants.ts, src/app/tracing/services/edit-tracing-settings.service.ts, src/app/tracing/tracing.actions.ts, src/app/tracing/tracing.effects.ts
Merging this will add an entry for the context menu when clicking on the emty canvas in tracing view, that unsets all Cross Contaminations.
=> #789 Context Menu "Cross Contamination"

src/app/tracing/configuration/filter-table-view/filter-table-view.component.ts
The onRowSelectionChange function was receiving unexpected parameters. This commit adjusts the function with aditional typeguards to prevent failing under those parameters.
Ticket: Silebat/fcl-client#792
=> Fix row selection bug.

src/app/tracing/graph/graph.service.ts
This fixes the bug described in
Ticket: Invisible station is cannot be made visible again in the graph #796
=> Fix the typeerror caused by accessing undefined.id in updateHoverEdges.

src/app/tracing/data.model.ts, src/app/tracing/graph/components/gis-graph/gis-graph.component.ts, src/app/tracing/graph/components/graph-legend-view/graph-legend-view.component.ts, src/app/tracing/graph/components/schema-graph/schema-graph.component.ts, src/app/tracing/services/highlighting.service.ts
Merging this commit will change the behaviour of the legend to be sorted by the index as the rules appear in the highliting rules table.
For rules that have both a Station and a Delivery rule, the lower of the two indecies is used.
Jumping can now only occur if a user deliberately sorts the delivery and station highliting rules differently.
Additionally the graphviewcomponent and highliting service functions that needed to be ajusted for this change where refactored.
Ticket: #785
=> Refine display of legend entries.

src/app/tracing/configuration/rule-conversion.ts, src/app/tracing/data.model.ts, src/app/tracing/dialog/deliveries-properties/deliveries-properties.component.ts, src/app/tracing/graph/graph.service.ts, src/app/tracing/io/data-exporter.ts, src/app/tracing/io/data-importer/data-importer-v1.ts, src/app/tracing/io/data-importer/shared.ts, src/app/tracing/services/highlighting.service.ts, src/app/tracing/services/table.service.ts, src/app/tracing/util/non-ui-utils.ts
This commit refactors the number[] color values in the internal parts or the app to use {r:number, g:number, b:number} instead.
This required minor updates to the default rules and the importer.
As part of this refactor, the multiple colorToCss functions strewn around the codebase have been changed to all use Utils.colorToCss.
Ticket: Refactor color #522
=> Refactor Color to be an object rather than an array.

src/app/tracing/dialog/station-properties/station-properties.component.ts, src/app/tracing/util/constants.ts
Merging this will cause deliveries to and from invisible station not to be shown in the properties tab of connected stations.
We should consider refactoring the station-properties-component to use more locally scoped variables and function return values, and reduce mutation of class variables to a minimum. Additionally the heavy use of the non-null-assertion operator should perhaps be reconsidered.
Ticket: Station property dialog shows hidden deliveries #417
=> Hide deliveries to invisible stations in station property diaglog.

package-lock.json, package.json
Reason: We want to use new TS features, such as the `satisfies` decorator.
Please run `npm install` and restart the development server to test this.
=> Ticket 833: Updated TypeScript Version.

package-lock.json, package.json, src/app/main-page/main-page.module.ts, src/app/tracing/configuration/filter-table-view/filter-table-utils.ts, src/app/tracing/configuration/filter-table-view/filter-table-view.component.ts, src/app/tracing/configuration/ngxdatatable-row-event-provider.directive.ts, src/app/tracing/configuration/sortable-header-cell-view.component.ts, src/app/tracing/dialog/deliveries-properties/deliveries-properties.component.ts, src/app/tracing/shared/ngxdatatable-scroll-fix.directive.ts, src/app/tracing/tracing.module.ts, src/ngx-datatable-style.scss, src/styles.scss
replaces dependency @swimlane/ngx-datatable v20.1.0 with @siemens/ngx-datatable v21.3.2
adds global ngx-datatable style adjustment (v21.2.0 introduced a row bottom border) to prevent row bottom borders
Background: Since Firefox v126 rows in the filtertable were overlaying each other. But @swimlane/ngx-datatable seems to be maintained not anymore (last release 2022, no maintainer feedback to reported issues). @siemens/ngx-datatable was forked of @swimlane/ngx-datatable because of the lacking maintenance.
ticket: #782
=> fixes row overlay in firefox browsers

package-lock.json, package.json
This updates the rimraf version we have added as a dependency for the clean command to a version > 4, as older versions are no longer supported. This will NOT update the versions angular uses, as they are tied to angulars version.
To test: run npm install and then the clean command
=> Updates rimraf dependency to v > 4.0.0

src/app/main-page/presentation/toolbar-action/toolbar-action.component.html
The button is currently disabled and a tooltip informs the user that this feature will soon be available. Please remove tooltip and enable button once we've activated the UTX upload.
Ticket #887
=> Adds UTX upload button

src/app/main-page/container/toolbar-action-container/toolbar-action-container.component.html, src/app/main-page/container/toolbar-action-container/toolbar-action-container.component.ts, src/app/main-page/presentation/toolbar-action/toolbar-action.component.html, src/app/main-page/presentation/toolbar-action/toolbar-action.component.ts
In Safari, users were only able to upload data when no example or other data had been loaded before.This was due to the input type=file being programmatically triggered in an async function, which is a security violation for safari. This moves the check the async function performs onto the upload menu opening button, so that we don't lose the trusted context for the input type=file click.
Ticket: #761
=> Fixes upload model bug in safari

src/styles.scss
This will fix the color of disabled buttons in the action toolbar to match that of the graph type selection.
Correction to Ticket: At login grey out all buttons which cannot be used without data #877
=> Fix color of disabled buttons in action toolbar

src/app/main-page/container/toolbar-action-container/toolbar-action-container.component.html, src/app/main-page/container/toolbar-action-container/toolbar-action-container.component.ts, src/app/main-page/presentation/toolbar-action/toolbar-action.component.html, src/app/main-page/presentation/toolbar-action/toolbar-action.component.scss, src/app/main-page/presentation/toolbar-action/toolbar-action.component.ts, src/app/tracing/dialog/dialog-import-warnings/dialog-import-warnings.component.html, src/app/tracing/dialog/dialog-import-warnings/dialog-import-warnings.component.scss, src/app/tracing/dialog/dialog-import-warnings/dialog-import-warnings.component.ts, src/app/tracing/dialog/dialog-movable/dialog-movable.component.html, src/app/tracing/dialog/dialog-movable/dialog-movable.component.scss, src/app/tracing/dialog/dialog-movable/dialog-movable.component.ts, src/app/tracing/tracing.module.ts
The toolbar component can now receive props stating if a data upload resulted in warnings. If this prop is true, a warning symbol will be displayed next to the file name in the toolbar. When a user clicks on the symbol, a modal opens. The modal is currently empty but shall eventually display a list of warnings.
Ticket #888
=> Ticket #888: Adds data upload warnings symbol and modal - Part 1

src/app/main-page/container/toolbar-action-container/toolbar-action-container.component.html, src/app/main-page/container/toolbar-action-container/toolbar-action-container.component.ts, src/app/main-page/presentation/toolbar-action/toolbar-action.component.ts, src/app/tracing/dialog/dialog-import-warnings/dialog-import-warnings.component.html, src/app/tracing/dialog/dialog-import-warnings/dialog-import-warnings.component.ts, src/app/tracing/state/tracing.selectors.ts, src/app/tracing/tracing.actions.ts, src/app/tracing/tracing.effects.ts
If warnings occurred during data import, a red warning sign is visible next to the file name. Clicking on that warning sign opens a dialog displaying a list of warnings. Warnings without text will be displayed as 'unknown warning'."
Ticket #900
=> Subtask 900: Adds data import warnings to warnings modal

src/app/tracing/io/data-importer/xlsx-import/all-in-one/importer.ts
Stations where registered twice, which caused deliveries to not consider them valid source or target. Because of this all deliveries where ommitted with warning in import.
Ticket: #926
=> Fix bug causing stations to be registered twice.

src/app/tracing/dialog/station-properties/station-properties.component.html, src/app/tracing/dialog/station-properties/station-properties.component.ts, src/material-style.scss
Text in svg in stations properties modal will now be truncated if it is longer than the rectangle it is rendered in. When hovering over a rectangle, a tooltip shows the entire text content.
Ticket #804
=> Ticket 804: Fixes text overflow in stations properties svg

src/material-style.scss, src/styles.scss
Warning toaster has a stronger background color now to improve visibility. The duplicate styles for the snackbar toasters in styles.scss have been removed. The original styles in material-styles.scss have been marked with !important, to ensure that they are not overwritten.
Ticket #949
=> Ticket #949: Changes color of warning toaster
